BoxLayout:
    orientation: 'vertical'
#    orientation: 'horizontal'
    padding: 20
    spacing: 10
    Button:
        text: 'Clear'
        on_press: app.handle_clear()
    TextInput:
        text: 'Greet'
        on_press: app.handle_greet()

    Button:
        text: 'Greet'
        on_press: app.handle_greet()
    Label:
        id: output_label
        text: 'Enter your name'
        color: (1, 1, 0, 1)